# Generated by Django 4.0.1 on 2022-02-15 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0002_rename_descr_tasks_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_Task', models.CharField(blank=True, help_text='Escreva aqui o tipo de sua task', max_length=55, null=True)),
                ('date_of_create', models.DateTimeField(auto_now_add=True)),
                ('Task_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
