# Generated by Django 4.0.1 on 2022-02-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_alter_tasks_options_delete_typeoftask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['task_done'], 'verbose_name': 'Tarefa'},
        ),
    ]
